### ISSUE TITLE
Normalizing shouldn't trigger DNS lookups

### ISSUE THREAD

**Issue by benedikt** [afair/email_address#20]
When normalizing an email address not hosted with a known provider, the gem will trigger a DNS lookup. While I love the ability to check MX records during validation, it's a huge performance impact when normalizing several email addresses. This happens often when using the email address type in ActiveRecord for example. 

To reproduce this issue, follow these steps in irb or so: 

```ruby
# Trigger an exception when an attempt to lookup DNS is made
class Resolv::DNS; def self.open(*args); raise "Please don't do that"; end; end

# Look up a random email address 
EmailAddress.normal("hello@example.com")
```

The problem seems to be related to finding the correct provider for the email address. Here's a backtrace for the example above:

```
email_address-0.1.8/lib/email_address/exchanger.rb:48:in `mxers'
email_address-0.1.8/lib/email_address/exchanger.rb:29:in `each'
email_address-0.1.8/lib/email_address/exchanger.rb:87:in `block in matches?'
email_address-0.1.8/lib/email_address/exchanger.rb:83:in `each'
email_address-0.1.8/lib/email_address/exchanger.rb:83:in `matches?'
email_address-0.1.8/lib/email_address/exchanger.rb:38:in `block in provider'
email_address-0.1.8/lib/email_address/exchanger.rb:37:in `each'
email_address-0.1.8/lib/email_address/exchanger.rb:37:in `provider'
email_address-0.1.8/lib/email_address/host.rb:220:in `find_provider'
email_address-0.1.8/lib/email_address/host.rb:177:in `host_name='
email_address-0.1.8/lib/email_address/host.rb:132:in `parse'
email_address-0.1.8/lib/email_address/host.rb:91:in `initialize'
email_address-0.1.8/lib/email_address/address.rb:30:in `new'
email_address-0.1.8/lib/email_address/address.rb:30:in `initialize'
email_address-0.1.8/lib/email_address.rb:43:in `new'
email_address-0.1.8/lib/email_address.rb:43:in `block (2 levels) in singleton class'
```

**Comment by afair** [comment]
Sounds reasonable. 👍  I'll check it out

**Comment by benedikt** [comment]
@afair Any news on this? I'm more than happy to help out with this. I probably need a pointer on where to start digging, though. Do you have time to chat about this?
