### ISSUE TITLE
Undefined method when host_validation mode is "syntax"

### ISSUE THREAD

**Issue by martinstreicher** [afair/email_address#26]
I recently added this to my code: 

```
EmailAddress::Config.configure(
  host_validation: :syntax
)
```

When I try to use `EmailAddress` to validate an address, an error occurs:

```
 3) Msb::CartsController checkout action failure email address is invalid returns 422
     Failure/Error: return if EmailAddress.valid?(email_address)
     
     NoMethodError:
       undefined method `mx_ips' for nil:NilClass
     # /Users/strike/.rvm/gems/ruby-2.4.2@memberhub-commerce-api/gems/email_address-0.1.9/lib/email_address/host.rb:417:in `valid_mx?'
     # /Users/strike/.rvm/gems/ruby-2.4.2@memberhub-commerce-api/gems/email_address-0.1.9/lib/email_address/host.rb:393:in `valid?'
     # /Users/strike/.rvm/gems/ruby-2.4.2@memberhub-commerce-api/gems/email_address-0.1.9/lib/email_address/address.rb:233:in `valid?'
     # /Users/strike/.rvm/gems/ruby-2.4.2@memberhub-commerce-api/gems/email_address-0.1.9/lib/email_address.rb:43:in `public_send'
     # /Users/strike/.rvm/gems/ruby-2.4.2@memberhub-commerce-api/gems/email_address-0.1.9/lib/email_address.rb:43:in `block (2 levels) in singleton class'
```

This is the line that blows up:

```
if self.exchangers.mx_ips.size > 0
```

Because this...

```
def exchangers
  return nil if @config[:host_type] != :email || !self.dns_enabled?
  @_exchangers ||= EmailAddress::Exchanger.cached(self.dns_name)
end
```

... returns `nil`.

**Comment by martinstreicher** [comment]
And it looks as if `host_validation` is something other than `:mx` or `:a`, then DNS is disabled.

**Comment by jaxn** [comment]
Also running into this while trying to disable `host_validation` in a unit test.

**Comment by afair** [comment]
Looks like #28 fixes this. My quick test of this case worked. Please re-open if it didn't
