### ISSUE TITLE
Tests fails on current `master`

### ISSUE THREAD

**Issue by AlexWayfer** [afair/email_address#74]
Hello.

I wanted to contribute (and resolve some issues), but the problem is that current `master` (commit 1e5a2edd31d3191d3d92ccc0f96ce6f2ca0eebe7) has failing tests:

```
> bundle exec rake
/home/alex/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/activesupport-5.2.5/lib/active_support/core_ext/hash/except.rb:12: warning: method redefined; discarding old except
Run options: --seed 34484

# Running:

...................../home/alex/Projects/ruby/email_address/lib/email_address/host.rb:336: warning: Socket.gethostbyname is deprecated; use Addrinfo.getaddrinfo instead.
......./home/alex/Projects/ruby/email_address/lib/email_address/host.rb:336: warning: Socket.gethostbyname is deprecated; use Addrinfo.getaddrinfo instead.
/home/alex/Projects/ruby/email_address/lib/email_address/host.rb:336: warning: Socket.gethostbyname is deprecated; use Addrinfo.getaddrinfo instead.
....../home/alex/Projects/ruby/email_address/lib/email_address/host.rb:336: warning: Socket.gethostbyname is deprecated; use Addrinfo.getaddrinfo instead.
................/home/alex/Projects/ruby/email_address/lib/email_address/host.rb:336: warning: Socket.gethostbyname is deprecated; use Addrinfo.getaddrinfo instead.
/home/alex/Projects/ruby/email_address/lib/email_address/host.rb:336: warning: Socket.gethostbyname is deprecated; use Addrinfo.getaddrinfo instead.
./home/alex/Projects/ruby/email_address/lib/email_address/host.rb:336: warning: Socket.gethostbyname is deprecated; use Addrinfo.getaddrinfo instead.
/home/alex/Projects/ruby/email_address/lib/email_address/host.rb:336: warning: Socket.gethostbyname is deprecated; use Addrinfo.getaddrinfo instead.
....................EF

Fabulous run in 24.147000s, 3.0231 runs/s, 9.4008 assertions/s.

  1) Error:
TestAR#test_validation:
ArgumentError: wrong number of arguments (given 1, expected 0)
    /home/alex/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/activemodel-5.2.5/lib/active_model/type/value.rb:8:in `initialize'
    /home/alex/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/activemodel-5.2.5/lib/active_model/type/registry.rb:12:in `new'
    /home/alex/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/activemodel-5.2.5/lib/active_model/type/registry.rb:12:in `block in register'
    /home/alex/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/activerecord-5.2.5/lib/active_record/type/adapter_specific_registry.rb:38:in `call'
    /home/alex/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/activemodel-5.2.5/lib/active_model/type/registry.rb:20:in `lookup'
    /home/alex/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/activerecord-5.2.5/lib/active_record/type.rb:42:in `lookup'
    /home/alex/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/activerecord-5.2.5/lib/active_record/attributes.rb:237:in `block in load_schema!'
    /home/alex/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/activerecord-5.2.5/lib/active_record/attributes.rb:235:in `each'
    /home/alex/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/activerecord-5.2.5/lib/active_record/attributes.rb:235:in `load_schema!'
    /home/alex/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/activerecord-5.2.5/lib/active_record/attribute_decorators.rb:51:in `load_schema!'
    /home/alex/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/activerecord-5.2.5/lib/active_record/model_schema.rb:459:in `block in load_schema'
    /home/alex/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/activerecord-5.2.5/lib/active_record/model_schema.rb:456:in `synchronize'
    /home/alex/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/activerecord-5.2.5/lib/active_record/model_schema.rb:456:in `load_schema'
    /home/alex/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/activerecord-5.2.5/lib/active_record/model_schema.rb:346:in `attribute_types'
    /home/alex/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/activerecord-5.2.5/lib/active_record/attribute_methods.rb:230:in `has_attribute?'
    /home/alex/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/activerecord-5.2.5/lib/active_record/inheritance.rb:55:in `new'
    /home/alex/Projects/ruby/email_address/test/activerecord/test_ar.rb:8:in `test_validation'

  2) Failure:
TestAR#test_datatype [/home/alex/Projects/ruby/email_address/test/activerecord/test_ar.rb:18]:
Expected: "pat.jones+asdf@gmail.com"
  Actual: "Pat.Jones+ASDF@GMAIL.com"

73 runs, 227 assertions, 1 failures, 1 errors, 0 skips
```

Current Bundle:

```
> bundle list
Gems included by the bundle:
  * activemodel (5.2.5)
  * activerecord (5.2.5)
  * activesupport (5.2.5)
  * arel (9.0.0)
  * concurrent-ruby (1.1.8)
  * docile (1.3.5)
  * email_address (0.1.20)
  * i18n (1.8.10)
  * minitest (5.14.4)
  * netaddr (2.0.4)
  * rake (13.0.3)
  * simplecov (0.21.2)
  * simplecov-html (0.12.3)
  * simplecov_json_formatter (0.1.2)
  * simpleidn (0.2.1)
  * sqlite3 (1.4.2)
  * thread_safe (0.3.6)
  * tzinfo (1.2.9)
  * unf (0.1.4)
  * unf_ext (0.0.7.7)
Use `bundle info` to print more detailed information about a gem
```

Sometimes there is no fail, only the error:

```
> bundle exec rake
/home/alex/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/activesupport-5.2.5/lib/active_support/core_ext/hash/except.rb:12: warning: method redefined; discarding old except
Run options: --seed 6383

# Running:

....../home/alex/Projects/ruby/email_address/lib/email_address/host.rb:336: warning: Socket.gethostbyname is deprecated; use Addrinfo.getaddrinfo instead.
/home/alex/Projects/ruby/email_address/lib/email_address/host.rb:336: warning: Socket.gethostbyname is deprecated; use Addrinfo.getaddrinfo instead.
........./home/alex/Projects/ruby/email_address/lib/email_address/host.rb:336: warning: Socket.gethostbyname is deprecated; use Addrinfo.getaddrinfo instead.
/home/alex/Projects/ruby/email_address/lib/email_address/host.rb:336: warning: Socket.gethostbyname is deprecated; use Addrinfo.getaddrinfo instead.
...........E........................../home/alex/Projects/ruby/email_address/lib/email_address/host.rb:336: warning: Socket.gethostbyname is deprecated; use Addrinfo.getaddrinfo instead.
/home/alex/Projects/ruby/email_address/lib/email_address/host.rb:336: warning: Socket.gethostbyname is deprecated; use Addrinfo.getaddrinfo instead.
./home/alex/Projects/ruby/email_address/lib/email_address/host.rb:336: warning: Socket.gethostbyname is deprecated; use Addrinfo.getaddrinfo instead.
.../home/alex/Projects/ruby/email_address/lib/email_address/host.rb:336: warning: Socket.gethostbyname is deprecated; use Addrinfo.getaddrinfo instead.
................

Fabulous run in 23.506989s, 3.1055 runs/s, 9.7418 assertions/s.

  1) Error:
TestAR#test_datatype:
ArgumentError: wrong number of arguments (given 1, expected 0)
    /home/alex/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/activemodel-5.2.5/lib/active_model/type/value.rb:8:in `initialize'
    /home/alex/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/activemodel-5.2.5/lib/active_model/type/registry.rb:12:in `new'
    /home/alex/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/activemodel-5.2.5/lib/active_model/type/registry.rb:12:in `block in register'
    /home/alex/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/activerecord-5.2.5/lib/active_record/type/adapter_specific_registry.rb:38:in `call'
    /home/alex/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/activemodel-5.2.5/lib/active_model/type/registry.rb:20:in `lookup'
    /home/alex/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/activerecord-5.2.5/lib/active_record/type.rb:42:in `lookup'
    /home/alex/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/activerecord-5.2.5/lib/active_record/attributes.rb:237:in `block in load_schema!'
    /home/alex/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/activerecord-5.2.5/lib/active_record/attributes.rb:235:in `each'
    /home/alex/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/activerecord-5.2.5/lib/active_record/attributes.rb:235:in `load_schema!'
    /home/alex/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/activerecord-5.2.5/lib/active_record/attribute_decorators.rb:51:in `load_schema!'
    /home/alex/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/activerecord-5.2.5/lib/active_record/model_schema.rb:459:in `block in load_schema'
    /home/alex/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/activerecord-5.2.5/lib/active_record/model_schema.rb:456:in `synchronize'
    /home/alex/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/activerecord-5.2.5/lib/active_record/model_schema.rb:456:in `load_schema'
    /home/alex/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/activerecord-5.2.5/lib/active_record/model_schema.rb:346:in `attribute_types'
    /home/alex/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/activerecord-5.2.5/lib/active_record/attribute_methods.rb:230:in `has_attribute?'
    /home/alex/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/activerecord-5.2.5/lib/active_record/inheritance.rb:55:in `new'
    /home/alex/Projects/ruby/email_address/test/activerecord/test_ar.rb:17:in `test_datatype'

73 runs, 229 assertions, 0 failures, 1 errors, 0 skips
```

I guess it's because some global state between tests, which is definitely bad.

If I'll have time — I can try to investigate, but it'd be easier for you, maintainer.

**Comment by AlexWayfer** [comment]
I've found that the reason of error is in Ruby 3. I'm preparing a PR.
